base_url = "https://chain-reaction.bike"
theme = "community-onepager"
description = "Community Bike Workshop"
compile_sass = false
minify_html = true
generate_feed = true

default_language = "en"

taxonomies = [
    {name = "tags", feed = true},
]

[languages.en]
weight = 1
title = "Chain Reaction"
languageName = "English"
languageCode = "en"
relativeURL = false

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Luisito"
favicon = "favicon.ico"
image = ""
list_pages = false
twitter_card = false

[[extra.header_nav]]
en = { name = "/home/", url = "/" }

[[extra.header_nav]]
en = { name = "/about/", url = "/about"}

